#include <iostream>

int main()
{
	std::cout << "Client Main moudle" << std::endl;
	return 0;
}

//abseil:x64-windows                                20240722.0          Abseil is an open-source collection of C++ libra...
//bzip2:x64-windows                                 1.0.8#6             bzip2 is a freely available, patent free, high-q...
//bzip2[tool]:x64-windows                                               Builds bzip2 executable
//c-ares:x64-windows                                1.34.2              A C library for asynchronous DNS requests
//expat:x64-windows                                 2.6.3               XML parser library written in C
//fmt:x64-windows                                   11.0.2#1            {fmt} is an open-source formatting library provi...
//grpc:x64-windows                                  1.60.0#1            gRPC is a modern, open source, high-performance ...
//grpc[codegen]:x64-windows                                             Build code generator machinery
//libffi:x64-windows                                3.4.6               Portable, high level programming interface to va...
//liblzma:x64-windows                               5.6.3               Compression library with an API similar to that ...
//openssl:x64-windows                               3.4.0               OpenSSL is an open source project that provides ...
//pkgconf:x64-windows                               2.3.0               pkgconf is a program which helps to configure co...
//protobuf:x64-windows                              4.25.1#1            Google's language-neutral, platform-neutral, ext...
//python3:x64-windows                               3.11.10             The Python programming language
//python3[extensions]:x64-windows                                       Allow the build and usage of python extensions. ...
//re2:x64-windows                                   2024-07-02          RE2 is a fast, safe, thread-friendly alternative...
//spdlog:x64-windows                                1.15.0              Very fast, header-only/compiled, C++ logging lib...
//sqlite3:x64-windows                               3.47.0#2            SQLite is a software library that implements a s...
//sqlite3[json1]:x64-windows                                            Enable JSON functionality for sqlite3
//upb:x64-windows                                   4.25.1#1            μpb (often written 'upb') is a small protobuf i...
//utf8-range:x64-windows                            4.25.1              Fast UTF-8 validation with Range algorithm (NEON...
//vcpkg-boost:x64-windows                           2024-05-15
//vcpkg-cmake-config:x64-windows                    2024-05-23
//vcpkg-cmake-get-vars:x64-windows                  2024-09-22
//vcpkg-cmake:x64-windows                           2024-04-23
//vcpkg-get-python:x64-windows                      2024-06-22
//vcpkg-msbuild:x64-windows                         2023-08-08
//vcpkg-pkgconfig-get-modules:x64-windows           2024-04-03
//vcpkg-tool-meson:x64-windows                      1.6.0               Meson build system
//zlib:x64-windows                                  1.3.1               A compression library
//zstd:x64-windows                                  1.5.6               Zstandard - Fast real-time compression algorithm
